# -*- coding: utf-8 -*-
"""SNN1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJw-y0EH-079IggJEPpVJsM22jS4995W
"""

!pip install brian2

from brian2 import *
import matplotlib.pyplot as plt

start_scope()

# Define model equations
eqs = '''
dv/dt = (I - v) / (10*ms) : 1
I : 1
'''

# Create 10 neurons with random input
G = NeuronGroup(10, eqs, threshold='v>1', reset='v=0', method='exact')
G.I = '0.7 + 0.5*rand()'

# Record spikes and voltages
M = StateMonitor(G, 'v', record=True)
spikemon = SpikeMonitor(G)

# Run the simulation
run(100*ms)

# Plot membrane potential over time
plt.figure(figsize=(12, 3))
for i in range(5):  # show only first 10 neurons
    plt.plot(M.t/ms, M.v[i], label=f'Neuron {i}')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane potential')
plt.legend()
plt.show()

# Raster plot (spike times)
plt.figure(figsize=(8, 4))
plt.plot(spikemon.t/ms, spikemon.i, '.k')
plt.xlabel('Time (ms)')
plt.ylabel('Neuron index')
plt.title('Spike Raster Plot')
plt.show()

start_scope()

# Leaky Integrate-and-Fire model equations
eqs = '''
dv/dt = (I - v) / (10*ms) : 1  # membrane potential
I : 1  # input current
'''

# Create 10 neurons
G = NeuronGroup(10, eqs, threshold='v > 1', reset='v = 0', method='exact')

# Assign higher input current so neurons spike
G.I = '1.2 + 0.5*rand()'

# Record state variables and spikes
M = StateMonitor(G, 'v', record=True)
spikemon = SpikeMonitor(G)

# Run the simulation for 100 milliseconds
run(100*ms)



# Step 4: Plot membrane potential (with resets)
plt.figure(figsize=(12, 4))
for i in range(5):  # Show only 5 neurons for clarity
    plt.plot(M.t/ms, M.v[i], label=f'Neuron {i}')
plt.xlabel('Time (ms)')
plt.ylabel('Membrane potential')
plt.title('Neuron Membrane Potentials (with Spikes)')
plt.legend()
plt.grid(True)
plt.show()

# Step 5: Plot spike raster
plt.figure(figsize=(8, 4))
plt.plot(spikemon.t/ms, spikemon.i, '.k')
plt.xlabel('Time (ms)')
plt.ylabel('Neuron index')
plt.title('Spike Raster Plot')
plt.grid(True)
plt.show()